services:
  wordpress:
    image: wordpress:php8.4-fpm-alpine
    volumes:
      - wp_data:/var/www/html
      - "./wordpress-tidb-compatibility-plugin/tidb-compatibility/tidb-compatibility.php:/var/www/html/wp-content/mu-plugins/tidb-compatibility.php"
    environment:
      WORDPRESS_DB_HOST: '${TIDB_HOST}:${TIDB_PORT}'
      WORDPRESS_DB_NAME: '${TIDB_DB_NAME}'
      WORDPRESS_DB_PASSWORD: '${TIDB_PASSWORD}'
      WORDPRESS_DB_USER: '${TIDB_USER}'
      WORDPRESS_DB_COLLATE: 'utf8mb4_bin'
      WORDPRESS_CONFIG_EXTRA: |
        define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
        define('MYSQL_SSL_CA', '/etc/ssl/certs/ca-certificates.crt');
        define('DB_COLLATE', 'utf8mb4_bin');

  caddy:
    image: caddy:2.10.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - wordpress

volumes:
  wp_data: